<?php

if (!isset($_COOKIE['readit'])) { ?>
    <article class="disclaimer">
    <p><a class="cancel" href="/logger/reg/readit">X</a>
    This is a mobile-friendly version of a basic database-driven website first created circa 2009 to allow our clients to upload files. While not entirely essential in the era of drop-box et al but the endeavour developed the skills that would prove super useful when the company later added variable data printing to its portfolio of services.</p><p>After quite some time experimenting with Docker and AWS it <a href="https://dev.to/dbazhenov/how-to-develop-serverless-php-application-with-postgresql-database-with-vercel-and-neontech-for-free-dgl" target="_blank">turns out</a> I could host this thing for free on Vercel's Hobby Plan as a member of the <a href="https://php-app-vercel.vercel.app/tutorial" target="_blank">vercel community</a> had created a <a href="https://dev.to/nx1/vercel-php-php-84-php-85-18ch" target="_blank">runtime for php</a>, all very exciting. This did involve migrating the original mysql database to postgres - only slightly less stressful than I had imagined (tip don't have a table named user), I then soon discovered that given the stateless nature of runtimes any uploaded assets would not persist beyond the current session, and although there are of course solutions to address this I've opted not to do so as the site exists purely for demonstration purposes and I can sleep safe in the knowledge that it hasn't become a haven for unsavoury content of which there is no shortage apparently.</p>
    <p>The site imagined a series of users with a range of capabilities; a user simply allowed to browse, one that can manage files, another also allowed to update their credentials, admin users responsible for managing the former and finally self-admin users (freelancers).
        Encapsulating the behavior of these different users became the primary challenge of this update, and although it would have made it slightly slicker I've resisted adding client-side javascript favouring css for any visual tricks and as I've been fortunate enough to remain ambivalent about frameworks the site is roll-your-own PHP.</p>
    <p>Log in as <a href="/logger/reg/112">"jeff.tracy@tbsrgo.com"</a> (admin | password:fab) or <a href="/logger/reg/113">"penny@fab1.co.uk"</a> (freelancer | password:parker) and upload something fab, albeit fleeting.</p>
   
    </article>

<?php } ?>